export const quantAnalysisFixture = {
  source: 'futu-assistant',
  generated_at: '2026-07-15T10:00:00-04:00',
  rule_version: '2.2',
  disclaimer: '认知参考，禁止据此机械调参；历史统计不代表未来收益',
  context: {
    cnn_fear_greed: { score: 46.3, rating: 'neutral', available: true },
    ndx_valuation: { pe: 36.08, pe_percentile_5y: 83.12, zone: '偏高', available: true },
    soxx: { percentile: 98.71, method: 'price_ma_fallback', available: true },
    rebound: { base_date: '2026-03-30', status: 'repairing', available: true },
  },
  symbols: {
    SOXL: {
      available: true,
      gates: {
        low_zone: { passed: true, applicable: true, current_drawdown_pct: -63.29, threshold_pct: -28 },
        signal_triggered: {
          passed: false,
          applicable: true,
          recent_buy_signals: [{ name: 'near_prior_low', label: '接近前低', date: '2026-07-15' }],
        },
        position_gate: { passed: true, applicable: true, family_share_pct: 3.2, cap_pct: 8 },
        daily_fuse: { passed: true, applicable: true, buys_today: 0, max_new_buys: 2 },
        batch_available: { passed: true, applicable: true, next_batch: 2, batch_count: 3 },
        valuation: {
          passed: false,
          applicable: true,
          available: true,
          reason: 'SOXX 分位 98.7 高估',
          cnn: 46.3,
          ndx_percentile: 83.1,
          soxx_percentile: 98.7,
          stock_percentile: null,
        },
      },
      gates_passed: 4,
      gates_total: 6,
      signal_stats: {
        near_prior_low: {
          d5: { n: 19, win_rate: null, sample_insufficient: true },
          d20: { n: 20, win_rate: 0.55, sample_insufficient: false },
          d60: { n: 25, win_rate: 0.6, sample_insufficient: false },
        },
      },
      depth_stats: {
        level_pct: 60,
        win_rate_60d: null,
        n: 10,
        sample_insufficient: true,
        bear_included: true,
      },
    },
    AAPL: {
      available: true,
      depth_window: {
        applicable: true, open: true, current_pct: 22.5, threshold_pct: 21.7,
        price_session: 'afterhours', win_rate_60d: 0.68, n: 25,
        sample_insufficient: false, bear_included: true,
      },
      gates: {
        low_zone: { passed: true, applicable: false, current_drawdown_pct: -8.12, threshold_pct: -15 },
        signal_triggered: { passed: true, applicable: true, recent_buy_signals: [] },
        position_gate: { passed: true, applicable: true, family_share_pct: 2, cap_pct: 8 },
        daily_fuse: { passed: true, applicable: true, buys_today: 0, max_new_buys: 2 },
        batch_available: { passed: false, applicable: true, next_batch: null, batch_count: 3 },
        valuation: {
          passed: false,
          applicable: false,
          reference_only: true,
          available: true,
          reason: '个股 5 年 PE 分位尚未进入低位',
          cnn: 29,
          ndx_percentile: 83.1,
          soxx_percentile: 98.7,
          stock_percentile: 45,
        },
      },
      gates_passed: 3,
      gates_total: 5,
      signal_stats: {},
      depth_stats: null,
    },
    AMZN: {
      available: true,
      depth_window: {
        applicable: true, open: false, current_pct: 15.2, threshold_pct: 17.5,
        price_session: 'premarket', win_rate_60d: 0.59, n: 22,
        sample_insufficient: false, bear_included: true,
      },
      gates: {},
      gates_passed: 0,
      gates_total: 0,
      signal_stats: {},
      depth_stats: null,
    },
    SGOV: {
      available: false,
      error: '现金类不参与条件查询',
    },
  },
  holding_costs: {
    SOXL: {
      weighted_average_cost: 22.5,
      currency: 'USD',
      coverage: 'complete',
      auto_fill_allowed: true,
    },
  },
  panic_window: {
    applicable: true,
    state: 'firing',
    state_label: '疯狂提醒中',
    stop_reason: null,
    current_family_pct: 3.2,
    generated_at: '2026-07-17T09:31:00-04:00',
    symbols: {
      SOXL: {
        applicable: true,
        state: 'firing',
        state_label: '疯狂提醒中',
        stop_reason: null,
        depth: { open: true, current_pct: 63.29, threshold_pct: 27.1, label: '深度位', explanation: '当前回撤 63.29%，达到 27.10%' },
        panic: { open: true, threshold_pct: 10, label: '恐慌位', explanation: '当日恐慌阈值已触发', triggered_session: 'regular', triggered_at: '2026-07-17T09:31:00-04:00' },
        target: { target_pct: 20, current_pct: 3.2, progress_pct: 16, label: '3 倍族合计目标' },
        display: { title: '恐慌抢买窗口', state_label: '疯狂提醒中', depth_open_text: '深度位 ✓', panic_open_text: '恐慌位 ✓', progress_text: '目标 20% / 当前 3.2%' },
      },
    },
  },
  sell: {
    shadow: true,
    symbols: {
      MSFT: {
        family: 'MSFT',
        market_value: 5000,
        held_symbols: ['MSFT', 'MSFU'],
        repair: {
          status: 'repairing',
          base_date: '2026-03-30',
          window_open: false,
          priority: ['option', 'leveraged_2x', 'underlying'],
          source: 'rebound_cycle_state',
        },
        contentment: {
          available: true,
          triggered: true,
          asset_gain_pct: 18,
          qqq_gain_pct: 20,
          gap_vs_qqq_pct: -2,
          signal: 'near',
          minimum_reduction_pct: 50,
          observation: true,
        },
        convergence: {
          triggered: true,
          count: 6,
          minimum_assets: 5,
          symbols: ['MSFT', 'AAPL', 'NVDA', 'AMZN', 'META', 'GOOGL'],
          action: '清仓杠杆品种或调仓 SGOV，仅手动操作',
          observation: true,
        },
        playbook: {
          available: true,
          label: '个股',
          sell_steps: [
            { gain_min_pct: 5, gain_max_pct: 7, sell_position_pct: 2 },
            { gain_min_pct: 7, gain_max_pct: 10, sell_position_pct: 3 },
            { gain_min_pct: 10, gain_max_pct: 999, sell_position_pct: 4 },
          ],
          risk_first_order: ['option', 'leveraged_2x', 'underlying'],
        },
        recent_signals: [{ name: 'five_day_gain', label: '5日涨幅过热', date: '2026-07-15' }],
      },
    },
  },
  summary: {
    buy_ready: [{
      symbol: 'SOXL', kind: 'etf3x', reason: '深度位+恐慌位双开',
      drawdown_pct: -63.29, threshold_pct: -27.1, win_rate_60d: 0.6,
      n: 18, sample_insufficient: true, price_session: 'regular',
      panic_session: 'regular', excess_pct: 36.19,
    }],
    buy_near: [{
      symbol: 'AMZN', kind: 'stock', reason: '距自身深度阈值还差 2.30 点',
      gap_pct: 2.3, drawdown_pct: -15.2, threshold_pct: -17.5,
      win_rate_60d: 0.59, n: 22, sample_insufficient: false,
      price_session: 'premarket', panic_session: null,
    }],
    sell_ready: [{
      symbol: 'MSFT', trigger: '知足常乐',
      detail: '自基准日 +18.00% vs QQQ +20.00%', shadow: true,
    }],
    idle_symbols: ['AAPL'],
    idle_count: 1,
    depth_states: {
      AAPL: { status: 'ready', gap_pct: 0, excess_pct: 0.8, progress_pct: 100 },
      AMZN: { status: 'near', gap_pct: 2.3, excess_pct: 0, progress_pct: 86.857143 },
      SOXL: { status: 'ready', gap_pct: 0, excess_pct: 36.19, progress_pct: 100 },
    },
    generated_at: '2026-07-15T10:00:00-04:00',
  },
} as const;
